#! /usr/bin/env python
from gripit.app import App
import PyQt5.QtGui as QtGui
import sys

ARG_ROS = "--ros"

if __name__ == '__main__':
    global ARG_ROS

    sys.argv.append(ARG_ROS)
    print(sys.argv)
    app = QtGui.QApplication(sys.argv)
    ex = App(app)
    sys.exit(app.exec_())